version: '3'
services:

  api-gateway:
    build: api-gateway
    ports:
    - "8081:8081"
    environment:
      USERS_API: "http://users:5001"
      STORIES_API: "http://stories:5002"
      REACTIONS_API: ""
      STATISTICS_API: ""
      AUTH_API: "http://auth:5005"
    links:
      - auth
      - users
      - stories

  users:
    build: users
    ports:
    - "5001:5001"

  auth:
    build: auth
    ports:
    -  "5005:5005"
    environment:
      USERS_API: "http://users:5001"
    links:
      - users

  stories:
    build: stories
    ports:
      - "5002:5002"
    environment:
      USERS_API: "http://users:5001"

    links:
      - users



