version: '3'
services:

  api-gateway1:
    build: api-gateway
    ports:
      - "8082:8082"
    expose:
      - "8082"
    environment:
      FLASK_PORT: "8082"
      USERS_API: "http://users:5001"
      STORIES_API: "http://stories:5002"
      REACTIONS_API: "http://reactions:5003"
      STATISTICS_API: "http://statistics:5004"
      AUTH_API: "http://auth:5005"
    links:
      - statistics
      - auth
      - users
      - stories
      - reactions

  api-gateway2:
    build: api-gateway
    ports:
      - "8083:8083"
    expose:
      - "8083"
    environment:
      FLASK_PORT: "8083"
      USERS_API: "http://users:5001"
      STORIES_API: "http://stories:5002"
      REACTIONS_API: "http://reactions:5003"
      STATISTICS_API: "http://statistics:5004"
      AUTH_API: "http://auth:5005"
    links:
      - statistics
      - auth
      - users
      - stories
      - reactions

  users:
    build: users
    expose:
      - "5001"
    environment:
      FLASK_PORT: "5005"
      USERS_API: "http://users:5001"
      STORIES_API: "http://stories:5002"
      REACTIONS_API: "http://reactions:5003"
      STATISTICS_API: "http://statistics:5004"
      AUTH_API: "http://auth:5005"
    ports:
    - "5001:5001"

  auth:
    build: auth
    ports:
      - "5005:5005"
    expose:
      - "5005"
    environment:
      FLASK_PORT: "5005"
      USERS_API: "http://users:5001"
      STORIES_API: "http://stories:5002"
      REACTIONS_API: "http://reactions:5003"
      STATISTICS_API: "http://statistics:5004"
      AUTH_API: "http://auth:5005"
    links:
      - users

  stories:
    build: stories
    ports:
      - "5002:5002"
    expose:
      - "5002"
    environment:
      USERS_API: "http://users:5001"
      REACTIONS_API: "http://reactions:5003"
    links:
      - users
      - redis-queue

  nginx-gateway:
    build: ./nginx
    links:
      - api-gateway1
      - api-gateway2
    ports:
      - '8081:8081'

  reactions:
    build: ./reactions
    ports:
      - "5003:5003"
    expose:
      - "5003"
    environment:
      FLASK_PORT: "5003"
      USERS_API: "http://users:5001"
      STORIES_API: "http://stories:5002"
      REACTIONS_API: "http://reactions:5003"
      STATISTICS_API: "http://statistics:5004"
      AUTH_API: "http://auth:5005"
      REDIS_URL: "redis://redis-queue:6379/0"
    links:
      - users
      - stories
      - redis-queue

  statistics:
    build: statistics
    ports:
      - "5004:5004"
    expose:
      - "5004"
    environment:
      FLASK_PORT: "5004"
      USERS_API: "http://users:5001"
      STORIES_API: "http://stories:5002"
      REACTIONS_API: "http://reactions:5003"
      STATISTICS_API: "http://statistics:5004"
      AUTH_API: "http://auth:5005"
      REDIS_URL: "redis://redis-queue:6379/0"
    links:
      - stories
      - users

  reactions-beat:
    build: reactions
    command: "python celery_entry.py beat --loglevel=INFO"
    environment:
      USERS_API: "http://users:5001"
      STORIES_API: "http://stories:5002"
      REACTIONS_API: "http://reactions:5003"
      STATISTICS_API: "http://statistics:5004"
      AUTH_API: "http://auth:5005"
      REDIS_URL: "redis://redis-queue:6379/0"
    links:
      - stories
      - users
      - redis-queue

  reactions-worker:
    build: reactions
    command: "python celery_entry.py worker --loglevel=INFO"
    environment:
      USERS_API: "http://users:5001"
      STORIES_API: "http://stories:5002"
      REACTIONS_API: "http://reactions:5003"
      STATISTICS_API: "http://statistics:5004"
      AUTH_API: "http://auth:5005"
      REDIS_URL: "redis://redis-queue:6379/0"
    depends_on:
      - reactions-beat
    links:
      - stories
      - users
      - redis-queue

  statistics-beat:
    build: statistics
    command: "python celery_entry.py beat --loglevel=INFO"
    environment:
      USERS_API: "http://users:5001"
      STORIES_API: "http://stories:5002"
      REACTIONS_API: "http://reactions:5003"
      STATISTICS_API: "http://statistics:5004"
      AUTH_API: "http://auth:5005"
      REDIS_URL: "redis://redis-queue:6379/0"
    links:
      - stories
      - users
      - redis-queue

  statistics-worker:
    build: statistics
    command: "python celery_entry.py worker --loglevel=INFO"
    environment:
      USERS_API: "http://users:5001"
      STORIES_API: "http://stories:5002"
      REACTIONS_API: "http://reactions:5003"
      STATISTICS_API: "http://statistics:5004"
      AUTH_API: "http://auth:5005"
      REDIS_URL: "redis://redis-queue:6379/0"
    depends_on:
      - statistics-beat
    links:
      - stories
      - users
      - redis-queue

  redis-queue:
    image: "redis:latest"
    expose:
      - "6379"
    ports:
      - "6379:6379"
