version: '3'
services:

  api-gateway:
    build: api-gateway
    ports:
    - "8080:5000"
    environment:
      USERS_ENDPOINT: "http://localhost:5001"
      STORIES_ENDPOINT: ""
      REACTIONS_ENDPOINT: ""
      STATISTICS_ENDPOINT: ""
      AUTH_ENDPOINT: "http://localhost:5005"

  users:
    build: users
    ports:
    - "5001:5000"

  auth:
    build: auth
    ports:
    -  "5005:5005"
    environment:
      USERS_API: "http://localhost:5001"

