version: '3'
services:

  api-gateway1:
    build: api-gateway
    ports:
      - "8082:8082"
    expose:
      - "8082"
    environment:
      FLASK_PORT: "8082"
      USERS_API: "http://users:5001"
      STORIES_API: ""
      REACTIONS_API: ""
      STATISTICS_API: ""
      AUTH_API: "http://auth:5005"
    links:
      - auth
      - users

  api-gateway2:
    build: api-gateway
    ports:
      - "8083:8083"
    expose:
      - "8083"
    environment:
      FLASK_PORT: "8083"
      USERS_API: "http://users:5001"
      STORIES_API: ""
      REACTIONS_API: ""
      STATISTICS_API: ""
      AUTH_API: "http://auth:5005"
    links:
      - auth
      - users

  users:
    build: users
    environment:
      FLASK_PORT: "5001"
      USERS_API: "http://users:5001"
      STORIES_API: ""
      REACTIONS_API: ""
      STATISTICS_API: ""
      AUTH_API: "http://auth:5005"
    ports:
    - "5001:5001"

  auth:
    build: auth
    ports:
    -  "5005:5005"
    environment:
      FLASK_PORT: "5005"
      USERS_API: "http://users:5001"
      STORIES_API: ""
      REACTIONS_API: ""
      STATISTICS_API: ""
      AUTH_API: "http://auth:5005"
    links:
      - users

  nginx-gateway:
    build: ./nginx
    links:
      - api-gateway1
      - api-gateway2
    ports:
      - '8081:8081'
